name: university-attendance-system
region: nyc

services:
  - name: web
    github:
      repo: sidowxyz/university-attendance-system
      branch: main
      deploy_on_push: true
    
    dockerfile_path: Dockerfile
    
    build_command: ""
    
    envs:
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: BUILD_TIME
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: BUILD_TIME
        type: SECRET
    
    http_port: 3000
    
    instance_count: 1
    instance_size_slug: basic-xxs
